# Generated by Django 3.1.4 on 2021-01-24 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Почта')),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='cloth_shop/media/images/logo_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cloth_type', models.CharField(choices=[('all', 'Все'), ('t-shirts', 'Футболки'), ('hoodie', 'Худи'), ('polo', 'Поло'), ('shirts', 'Рубашки')], max_length=15)),
                ('main_photo', models.ImageField(default='no_photo.png', upload_to='cloth_shop/media/images/main_photos')),
                ('price', models.FloatField()),
                ('season', models.CharField(choices=[('1', 'Любой'), ('2', 'Лето'), ('3', 'Зима'), ('4', 'Осень'), ('5', 'Весна')], max_length=10)),
                ('sold', models.IntegerField(default=0)),
                ('release', models.DateField(default=django.utils.timezone.now)),
                ('amount_XS', models.IntegerField(default=0)),
                ('amount_S', models.IntegerField(default=0)),
                ('amount_M', models.IntegerField(default=0)),
                ('amount_L', models.IntegerField(default=0)),
                ('amount_XL', models.IntegerField(default=0)),
                ('amount_XXL', models.IntegerField(default=0)),
                ('brand', models.ManyToManyField(related_name='products', to='cloth_shop.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cloth_shop/media/images/product_photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cloth_shop.product')),
            ],
        ),
    ]
